# # # # # # # # # # # # # # # # # # # #
#     Minecast Configuration          #
#    By drtshock and Shadowwolf97     #
# # # # # # # # # # # # # # # # # # # #

# Auto update
# This option allows us to check for updates.
# We recommend always leaving this to true so you can
# keep up to date with the latest bug fixes.
auto-update: true

# Check for updates
# This will allow us to just check for updates
# and link you to the download and changelog.
# We advise you to never disable both this and auto updates.
# If auto-update is set to true then this option will do nothing.
check-update: true

# TWEET EXPIRE
# Once a new PendingTweet object is created, how long does a user have to confirm
#   sending the tweet?
# Length in tickets. 100 = 5 seconds.
tweet-expire: 100

# The server's API key
api-key: 'e53a9aeb_4d3a4c715f02ea9a1a6a5aec66f030e1'

lang:
    # Sent as the prefix to every message.
    title: '&7[&bMinecast&7] '

    # Sent when a tweet fails to send.
    tweet_error: '&cThere was an error sending your tweet.'

    # Sent when a player successfully sends a tweet.
    tweet_success: '&aYour tweet has been sent successfully!.'

    # Sent to the player when they attempt to tweet from an untrusted server.
    not_trusted: '&cClick the link below before you can tweet on this server.'

    # Sends the link to the player to add the server to their trusted list.
    # =trust_url= - the trust URL.
    not_trusted_url: '&7=trust_url='

    # Sent to the player when they try to tweet from an account that is not.
    # Linked to a Minecast account.
    unlinked_account: '&cYour minecraft account isnt linked to a twitter account. Signup at &7http://minecast.io/'

    # Sent to the player when they try to tweet but they have no pending tweets
    no_pending: '&cYou have no pending tweets.'

    # Sent to the player when they cancel a pending tweet
    pending_cancel: '&7You have cancelled your pending tweet.'

    # Sent to the player when ever you try to have a player send a tweet.
    # =tweet= - tweet to send.
    pending-tweet:
      - "&b------------------------------------"
      - " "
      - "&7Would you like to tweet:"
      - "=tweet="
      - " "
      - "&6Type &a/yes &6to confirm or &c/no &6 to cancel."
      - " "
      - "&b------------------------------------"